'use strict';
const assert=require('node:assert/strict'),{randomUUID,randomBytes}=require('node:crypto'),{readFileSync}=require('node:fs'),{join}=require('node:path');
const express=require('express'),{PGlite}=require('@electric-sql/pglite');
const {PgStore}=require('../lib/capture/store'),{WorkspaceStore,hash}=require('../lib/workspace/store'),{OfferStore}=require('../lib/offers/store'),{createWorkspaceRuntime}=require('../lib/workspace/runtime');
let checks=0;async function check(name,fn){await fn();console.log(`ok ${++checks} - ${name}`);}
async function main(){const db=new PGlite();let tail=Promise.resolve(),server;async function acquire(){let release;const before=tail;tail=new Promise(r=>release=r);await before;return release;}
 const query=(sql,args)=>args===undefined?db.exec(sql).then(r=>r.at(-1)):db.query(sql,args),pool={async query(sql,args){const release=await acquire();try{return await query(sql,args);}finally{release();}},async connect(){const release=await acquire();return {query,release};}};
 let clock=Date.UTC(2026,8,25,13),key=randomBytes(32).toString('base64url'),cookie='',csrf='';const now=()=>clock,origin='https://offers.example.invalid';
 const cfg={alpha:{enabled:true,offersEnabled:true,name:'Synthetic Alpha',keyHash:hash(key)},beta:{enabled:true,offersEnabled:false,name:'Synthetic Beta',keyHash:hash(randomBytes(32).toString('base64url'))}};
 const env={JEMLIO_WORKSPACE_ENABLED:'true',JEMLIO_WORKSPACE_ORIGIN:origin,JEMLIO_WORKSPACE_CONFIG:JSON.stringify(cfg),JEMLIO_OFFERS_ENABLED:'true'};
 const capture=new PgStore({pool}),workspace=new WorkspaceStore({pool,now}),store=new OfferStore({pool,now});
 const allowed=client=>cfg[client]?.offersEnabled===true;
 async function entry(client='alpha'){const id=randomUUID();await capture.create({client,receipt:id,submissionId:randomUUID(),payloadHash:randomUUID(),createdAt:clock,data:{name:'Private customer',email:'private@example.invalid',phone:'12345678',message:'Private intake message',service:'visit',consent:true},notification:{to:['owner@example.invalid'],subject:'Never send',text:'Synthetic'}});return id;}
 const revision=async id=>(await workspace.list('alpha',{view:'all'})).items.find(r=>r.id===id).revision;
 const draft=async id=>({revision:await revision(id),title:'Synthetic proposal',description:'Synthetic service details only.',totalOre:890000,priceBasis:'incl_vat',days:7,verified:true});
 const issue=async id=>store.issue('alpha',id,await draft(id));
 async function call(path,body,headers={}){const r=await fetch('http://127.0.0.1:'+server.address().port+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie,'X-Jemlio-CSRF':csrf}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,headers:r.headers,data:await r.json()};}
 try{
  await capture.initialize();for(const part of ['booking','workspace','workspace'])await pool.query(readFileSync(join(__dirname,'../lib',part,'schema.sql'),'utf8'));
  const id=await entry(),beta=await entry('beta');let offer;
  await check('only reviewed, scoped proposals with bounded explicit prices can be issued',async()=>{const input=await draft(id);for(const patch of [{verified:false},{totalOre:-1},{totalOre:1.5},{priceBasis:'guess'},{days:31},{description:'x'},{extra:'no'}])await assert.rejects(store.issue('alpha',id,{...input,...patch}));await assert.rejects(store.issue('beta',id,input),/request_not_found/);await assert.rejects(store.issue('alpha',beta,input),/request_not_found/);assert.equal((await pool.query('SELECT * FROM jemlio_offers')).rows.length,0);offer=await store.issue('alpha',id,input);assert.match(offer.token,/^[a-f0-9]{64}$/);assert.equal(offer.offer.version,1);});
  await check('only token hashes persist; public response excludes customer and internal details',async()=>{const rows=(await pool.query('SELECT * FROM jemlio_offers')).rows;assert.notEqual(rows[0].token_hash,offer.token);assert.equal(rows[0].token_hash,hash(offer.token));const found=await store.readOffer(offer.token,allowed);const text=JSON.stringify(found);for(const value of ['private@example.invalid','Private customer','Private intake message','token_hash',offer.token])assert.equal(text.includes(value),false);assert.equal((await store.history('alpha',id)).items.length,1);await assert.rejects(store.history('beta',id),/request_not_found/);});
  await check('issuing sets a durable owner follow-up and a waiting offer without claiming delivery',async()=>{const row=(await workspace.list('alpha',{view:'offers'})).items[0];assert.equal(row.id,id);assert.equal(row.followup.action,'review');assert.equal(Date.parse(row.followup.due),clock+3*86400000);const report=await workspace.report({client:'alpha'});assert.equal(report.offers_waiting,1);assert.equal(report.won,0);assert.equal(report.sales_ore,'0');await assert.rejects(store.issue('alpha',id,{...await draft(id),revision:'a'.repeat(64)}),/conflict/);});
  await check('customer interest queues personal follow-up, never a sale, booking or second notification',async()=>{await store.respond(offer.token,{response:'interested',note:'Please call after 14.'},allowed);const row=(await workspace.list('alpha',{view:'offer_response'})).items[0];assert.equal(row.offer.response,'interested');assert.equal(row.followup.overdue,true);assert.equal(row.outcome,'new');const report=await workspace.report({client:'alpha'});assert.equal(report.offers_interested,1);assert.equal(report.offers_waiting,0);assert.equal(report.won,0);assert.equal(report.sales_ore,'0');assert.equal((await pool.query('SELECT * FROM jemlio_bookings')).rows.length,0);assert.equal((await pool.query('SELECT * FROM nova_capture_outbox WHERE request_id=$1',[id])).rows.length,1);});
  await check('lost acknowledgement can be replayed exactly; conflicting later responses cannot overwrite',async()=>{const again=await store.respond(offer.token,{response:'interested',note:'Please call after 14.'},allowed);assert.equal(again.state,'responded');await assert.rejects(store.respond(offer.token,{response:'declined',note:''},allowed),/response_conflict/);assert.equal((await pool.query("SELECT * FROM jemlio_offer_events WHERE action LIKE 'response_%'")).rows.length,1);});
  await check('new versions revoke all old links and preserve response history without tokens',async()=>{const previous=offer;offer=await issue(id);assert.equal(offer.offer.version,2);await assert.rejects(store.readOffer(previous.token,allowed),/offer_unavailable/);await assert.rejects(store.respond(previous.token,{response:'interested'},allowed),/offer_unavailable/);const history=await store.history('alpha',id);assert.equal(history.items[1].response,'interested');assert.equal(history.items[1].state,'superseded');assert.equal(JSON.stringify(history).includes('token'),false);});
  await check('explicit withdrawal, tenant disable, closed enquiries and expiry revoke public access',async()=>{await assert.rejects(store.readOffer(offer.token,()=>false),/offer_unavailable/);await store.withdraw('alpha',id,{revision:await revision(id)});await assert.rejects(store.readOffer(offer.token,allowed),/offer_unavailable/);offer=await issue(id);await pool.query("INSERT INTO nova_capture_outcomes(request_id,outcome,updated_at) VALUES ($1,'lost',$2)",[id,new Date(clock)]);await assert.rejects(store.readOffer(offer.token,allowed),/offer_unavailable/);await assert.rejects(issue(id),/request_closed/);await pool.query('DELETE FROM nova_capture_outcomes WHERE request_id=$1',[id]);clock+=8*86400000;await assert.rejects(store.readOffer(offer.token,allowed),/offer_unavailable/);assert.equal((await workspace.list('alpha',{view:'due'})).items[0].offer.state,'expired');});
  await check('deletion cascades proposals and audit, and cannot leave an accessible link',async()=>{const doomed=await entry(),q=await issue(doomed);await pool.query('DELETE FROM nova_capture_requests WHERE id=$1',[doomed]);await assert.rejects(store.readOffer(q.token,allowed),/offer_unavailable/);assert.equal((await pool.query('SELECT * FROM jemlio_offer_events WHERE request_id=$1',[doomed])).rows.length,0);});
  const runtime=createWorkspaceRuntime({env,pool,now}),app=express();app.use('/api/workspace',runtime.router);app.use('/api/offers',runtime.offerRouter);app.use('/disabled',createWorkspaceRuntime({env:{}}).offerRouter);server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  await check('owner API requires session, tenant scope, CSRF and feature activation',async()=>{const body=await draft(id);assert.equal((await call('/api/workspace/alerts')).status,401);assert.equal((await call('/api/workspace/enquiries/'+id+'/offer',body)).status,401);const login=await call('/api/workspace/login',{key});assert.equal(login.status,200);assert.equal(login.data.features.offers,true);cookie=login.headers.get('set-cookie').split(';')[0];csrf=login.data.csrf;assert.deepEqual((await call('/api/workspace/alerts')).data,{enabled:false});assert.equal((await call('/api/workspace/enquiries/'+id+'/offer',body,{'X-Jemlio-CSRF':''})).status,403);assert.equal((await call('/api/workspace/enquiries/'+beta+'/offer',body)).status,404);const r=await call('/api/workspace/enquiries/'+id+'/offer',body);assert.equal(r.status,200);assert.equal(r.data.sendsMessages,false);const url=new URL(r.data.shareUrl);assert.equal(url.origin,origin);assert.equal(url.search,'');offer={token:url.hash.slice(1),offer:r.data.offer};assert.equal((await call('/api/workspace/enquiries/'+id+'/offers')).status,200);});
  await check('customer API requires private token and exact origin; disabled integrations reveal nothing',async()=>{cookie='';csrf='';assert.equal((await call('/disabled/read',{token:offer.token})).status,503);assert.equal((await call('/api/offers/read',{token:offer.token},{Origin:'https://evil.invalid'})).status,403);assert.equal((await call('/api/offers/read',{token:offer.token},{Origin:''})).status,403);assert.equal((await call('/api/offers/read',{token:offer.token,client:'beta'})).status,400);assert.equal((await call('/api/offers/read',{token:'a'.repeat(64)})).status,404);const r=await call('/api/offers/read',{token:offer.token});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.data.business,'Synthetic Alpha');assert.equal(JSON.stringify(r.data).includes('private@example.invalid'),false);});
  await check('customer change requests require a note and durable follow-up; new responses change owner revisions',async()=>{const before=await revision(id);assert.equal((await call('/api/offers/respond',{token:offer.token,response:'changes'})).status,400);assert.equal((await call('/api/offers/respond',{token:offer.token,response:'changes',note:'Can we discuss the scope?'})).status,200);await assert.rejects(workspace.update('alpha',id,{revision:before,note:'Stale owner screen'},'test'),/conflict/);assert.equal((await workspace.list('alpha',{view:'offer_response'})).items[0].offer.response,'changes');});
  await check('rate limits apply to valid-format wrong-token guesses',async()=>{let status;for(let i=0;i<61;i++)status=(await call('/api/offers/read',{token:'b'.repeat(64)})).status;assert.equal(status,429);});
  console.log(`Offer workflow checks passed: ${checks}. Local synthetic data; no messages or payments.`);
 }finally{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await db.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
